### ISSUE TITLE
How do I send e object to progress function?

### ISSUE THREAD

**Issue by royhg** [englercj/jquery-ajax-progress#5]
Hi Chad,
How do I send XML/e object type to progress, if my request response type is html?

tq.
royhg

**Comment by englercj** [comment]
I'm not sure I understand the question. `e` is the event object that the browser creates for the XHR progress event.

**Comment by royhg** [comment]
Hi Chad,
Sorry for my questions,
If I send ajax request that returns html, 
how do I count el.dom inside has been retrieved by user during successful request?
like example if the data request is big that needs some time to wait untill complete..
My question is how do I count or catch successfull respons from server before it show to user?
tq.
royhg

**Comment by englercj** [comment]
All XHR requests are the same while in-flight, your data type doesn't matter. The `e` is the event from the browser that tells you how much data has downloaded and how much still needs to be downloaded. Until the download completes there is no context as to what the contents of the request are.

Are you experiencing an issue? Because the code on the README should be everything you should need.
